# Generated by Django 4.0.4 on 2022-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
